version: 2.1
orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1
jobs:
  build:
    working_directory: ~/jjwm-portfolio-client
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@5'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: lint
          command: npm run lint
      - run:
          name: test
          command: npm run test:cover
      - store_artifacts:
          path: coverage
          prefix: coverage
      - sonarcloud/scan

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
